name: peppermint_sdk
description: A flutter plugin that let you easily create and manage web3 wallet and support funcitionality of Peppermint
version: 1.0.0
homepage: https://github.com/adgorithmics-inc/peppermint-flutter-sdk

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^4.1.0
  cached_network_image: ^3.2.0
  camera: ^0.10.1
  colorfilter_generator: ^0.0.8
  file_picker: ^5.2.5
  flutter_colorpicker: ^1.0.3
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  hand_signature: ^3.0.1
  image: ^4.0.17
  image_editor: ^1.3.0
  image_editor_plus: ^0.2.3
  lottie: ^2.2.0
  mobile_scanner: ^3.2.0
  model_viewer_plus: ^1.3.3
  nb_utils: ^5.0.8
  path: ^1.0.1
  path_provider: ^2.0.9
  scan: ^1.6.0
  screenshot: ^2.1.0
  sentry_flutter: ^7.8.0
  video_player: ^2.4.9
  visibility_detector: ^0.4.0+2
  web3dart: ^2.3.5
  url_launcher: ^6.1.2
  image_cropper: ^4.0.1
  wallet_connect: ^1.0.4
  eth_sig_util: ^0.0.3
  http: ^0.13.5

dev_dependencies:
  test: ^1.17.0
  flutter_lints: ^2.0.1

# flutter pub publish --dry-run


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
   - assets/lottie/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
